AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to censor inappropriate text from images

Globals:
  Function:
    Timeout: 60

Parameters:
  ClientUri:
    Type: String
    Description: Uri of frontend  

Resources:
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: !Sub "'${ClientUri}'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  ContentModerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ContentModerationFunction
      PackageType: Image
      MemorySize: 256
      Environment:
        Variables:
          S3_PROCESSED_IMAGE_BUCKET_NAME: !Ref S3ProcessedImageBucket
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - S3ReadPolicy:
            BucketName: !Sub "image-moderation-${AWS::AccountId}"
        - S3WritePolicy:
            BucketName: !Ref S3ProcessedImageBucket
      Events:
        NewImageUpload:
          Type: S3
          Properties:
            Bucket: !Ref S3ImageUploadBucket
            Events: s3:ObjectCreated:Put
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./moderate_content/handler
      DockerTag: python3.8-v1

  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UploadRequestFunction
      PackageType: Image
      Environment:
        Variables:
          S3_PROCESSED_IMAGE_BUCKET_NAME: !Ref S3ProcessedImageBucket
          S3_IMAGE_BUCKET_NAME: !Sub "image-moderation-${AWS::AccountId}"
          CLIENT_URI: !Ref ClientUri
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3ProcessedImageBucket
        - S3CrudPolicy:
            BucketName: !Sub "image-moderation-${AWS::AccountId}"
      Events:
        UploadPublicImage:
          Type: Api
          Properties:
            Path: /upload/public
            Method: GET
            RestApiId: !Ref ServiceApi
            Auth:
              Authorizer: CognitoAuthorizer
        UploadPrivateImage:
          Type: Api
          Properties:
            Path: /upload/private
            Method: GET
            RestApiId: !Ref ServiceApi
            Auth:
              Authorizer: CognitoAuthorizer
        ViewPublicGallery:
          Type: Api
          Properties:
            Path: /view-image/public
            Method: GET
            RestApiId: !Ref ServiceApi
            Auth:
              Authorizer: CognitoAuthorizer     
        ViewPrivateImages:
          Type: Api
          Properties:
            Path: /view-image/private
            Method: GET
            RestApiId: !Ref ServiceApi
            Auth:
              Authorizer: CognitoAuthorizer
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./presigned_url/handler
      DockerTag: python3.8-v1

  S3ImageUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "image-moderation-${AWS::AccountId}"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - 'Content-Type'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins: 
              - !Ref ClientUri

  S3ProcessedImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - 'Content-Type'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins: 
              - !Ref ClientUri
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: image-app-user-pool
      AutoVerifiedAttributes: ['email']
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: False
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: image-app-user-pool-client
      GenerateSecret: False
      UserPoolId: !Ref CognitoUserPool

Outputs:
  ContentModerationApi:
    Description: "API Gateway endpoint URL for Prod stage for Content Moderation function"
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  ImageUploadBucket:
    Description: "S3 bucket for image uploads"
    Value: !Ref S3ImageUploadBucket

  ProcessedImageBucket:
    Description: "S3 bucket to store censored images"
    Value: !Ref S3ProcessedImageBucket
